### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jeanselme** [Jeanselme/Search_Engine#4]
Is a [Apache License 2.0](http://choosealicense.com/licenses/apache-2.0/) well adapted to this project ?

**Comment by clinm** [comment]
I just checked with NLTK library ([website here](http://www.nltk.org/book/)) and they are using a [creative commons licence](https://creativecommons.org/licenses/by-nc-nd/3.0/us/).

As we are not planning to modify NLTK, i guess it's ok.
I used [this website](https://creativecommons.org/choose/) and came up with [this licence](https://creativecommons.org/licenses/by-nc-sa/4.0/) for our project.
What do you think about it ?

**Comment by Jeanselme** [comment]
That is perfect for me !

**Comment by Jeanselme** [comment]
It is not proposed by GitHub by default. It is not an open source license I think. Shouldn't we use a GNU license ?

**Comment by Jeanselme** [comment]
It is not proposed by GitHub by default. It is not an open source license I think. Shouldn't we use a GNU license ?

**Comment by clinm** [comment]
Well, I checked the GPLv3 on [this website](http://choosealicense.com/licenses/gpl-3.0/).
Why not !

Assuming that we are taking this licence, are we doing the step further advised by the website ?

> Note: The Free Software Foundation recommends taking the additional step of adding a boilerplate notice to the top of each file. The boilerplate can be found at the end of the license.

In addition, I propose a short text in the readme. Something like : 

> If you want to participate, let us know ! If you are using our project in any way, we will be happy to hear about it =)

**Notes :** '=)' is mandatory :p

**Comment by Jeanselme** [comment]
I don't think that it is necessary to add the boilerplate, we have already put our names at the beginning of each file. 
And for the readme, why not ?
